module.exports = function (request, response) {
    response.json([
        {
            lyhytNimi: {
                fi: 'Opetushallitus',
                sv: 'Utbildningsstyrelsen',
                en: 'Finnish National Agency for Education',
            },
            muutKotipaikatUris: [],
            muutOppilaitosTyyppiUris: [],
            yhteystietoArvos: [],
            piilotettu: false,
            parentOidPath: '',
            oid: '1.2.246.562.10.00000000001',
            kieletUris: [],
            kuvaus2: {},
            maaUri: 'maatjavaltiot1_fin',
            nimet: [
                {
                    nimi: {
                        fi: 'Opetushallitus',
                        sv: 'Utbildningsstyrelsen',
                        en: 'Finnish National Agency for Education',
                    },
                    alkuPvm: '1970-01-01',
                    version: 0,
                },
            ],
            tyypit: ['organisaatiotyyppi_05'],
            vuosiluokat: [],
            lisatiedot: [],
            ryhmatyypit: [],
            kayttoryhmat: [],
            yhteystiedot: [],
            kayntiosoite: {},
            postiosoite: {},
            alkuPvm: '1970-01-01',
            nimi: { fi: 'Opetushallitus', sv: 'Utbildningsstyrelsen', en: 'Finnish National Agency for Education' },
            status: 'AKTIIVINEN',
            version: 0,
        },
        {
            lyhytNimi: {
                fi: 'CSC-Tieteen tietotekniikan keskus Oy',
                sv: 'CSC-Tieteen tietotekniikan keskus Oy',
                en: 'CSC-Tieteen tietotekniikan keskus Oy',
            },
            muutKotipaikatUris: [],
            muutOppilaitosTyyppiUris: [],
            yhteystietoArvos: [],
            yritysmuoto: 'Osakeyhtiö',
            piilotettu: false,
            parentOid: '1.2.246.562.10.00000000001',
            parentOidPath: '|1.2.246.562.10.00000000001|',
            oid: '1.2.246.562.10.2013112012294919827487',
            kieletUris: ['oppilaitoksenopetuskieli_1#1'],
            kotipaikkaUri: 'kunta_049',
            kuvaus2: {},
            maaUri: 'maatjavaltiot1_fin',
            metadata: {
                data: {
                    KANSAINVALISET_KOULUTUSOHJELMAT: {},
                    YLEISKUVAUS: {},
                    KIELIOPINNOT: {},
                    TERVEYDENHUOLTOPALVELUT: {},
                    TEHTAVANIMIKE: {},
                    SAHKOPOSTIOSOITE: {},
                    RAHOITUS: {},
                    AIEMMIN_HANKITTU_OSAAMINEN: {},
                    'sosiaalinenmedia_7#1': {},
                    'sosiaalinenmedia_5#1': {},
                    'sosiaalinenmedia_6#1': {},
                    OPISKELIJALIIKKUVUUS: {},
                    VAKUUTUKSET: {},
                    OPISKELIJA_JARJESTOT: {},
                    VALINTAMENETTELY: {},
                    'sosiaalinenmedia_3#1': {},
                    'sosiaalinenmedia_4#1': {},
                    'sosiaalinenmedia_1#1': {},
                    VASTUUHENKILOT: {},
                    KUSTANNUKSET: {},
                    OPPIMISYMPARISTO: {},
                    'sosiaalinenmedia_2#1': {},
                    PUHELINNUMERO: {},
                    NIMI: {},
                    OPISKELIJALIIKUNTA: {},
                    VUOSIKELLO: {},
                    OPISKELIJARUOKAILU: {},
                    VAPAA_AIKA: {},
                    ESTEETOMYYS: {},
                    TIETOA_ASUMISESTA: {},
                    TYOHARJOITTELU: {},
                },
                hakutoimistoEctsNimi: {},
                hakutoimistoEctsPuhelin: {},
                hakutoimistoEctsTehtavanimike: {},
                hakutoimistoEctsEmail: {},
                hakutoimistonNimi: {},
                yhteystiedot: [],
                luontiPvm: 1384943389930,
                muokkausPvm: 1384943389930,
                nimi: {},
            },
            nimet: [
                {
                    nimi: {
                        fi: 'CSC-Tieteen tietotekniikan keskus Oy',
                        sv: 'CSC-Tieteen tietotekniikan keskus Oy',
                        en: 'CSC-Tieteen tietotekniikan keskus Oy',
                    },
                    alkuPvm: '2008-08-28',
                    version: 0,
                },
            ],
            toimipistekoodi: '',
            tyypit: ['organisaatiotyyppi_05'],
            vuosiluokat: [],
            lisatiedot: [],
            ryhmatyypit: [],
            kayttoryhmat: [],
            ytjkieli: 'kieli_fi#1',
            ytjpaivitysPvm: '2017-04-18',
            ytunnus: '0920632-0',
            yhteystiedot: [
                {
                    kieli: 'kieli_fi#1',
                    numero: '050 82884811',
                    tyyppi: 'puhelin',
                    yhteystietoOid: '1.2.246.562.5.2013112012294919858701',
                    id: '1107723',
                },
                {
                    kieli: 'kieli_fi#1',
                    yhteystietoOid: '1.2.246.562.5.2013112012294919826997',
                    id: '1107724',
                    email: 'hakija-47898286@oph.fi',
                },
                {
                    osoiteTyyppi: 'kaynti',
                    kieli: 'kieli_fi#1',
                    postinumeroUri: 'posti_02100',
                    yhteystietoOid: '1.2.246.562.5.2013112012294919890347',
                    id: '1107722',
                    maaUri: '',
                    postitoimipaikka: 'ESPOO',
                    osoite: 'Kökköpolku 980',
                    ytjPaivitysPvm: '2015-01-31',
                },
                {
                    osoiteTyyppi: 'posti',
                    kieli: 'kieli_fi#1',
                    postinumeroUri: 'posti_02101',
                    yhteystietoOid: '1.2.246.562.5.2013112012294919824794',
                    id: '1107721',
                    maaUri: '',
                    postitoimipaikka: 'ESPOO',
                    osoite: 'Horonpohjantie 530',
                    ytjPaivitysPvm: '2017-04-18',
                },
                {
                    kieli: 'kieli_fi#1',
                    www: 'http://www.csc.fi',
                    yhteystietoOid: '1.2.246.562.5.2013112012294919834571',
                    id: '1107725',
                },
            ],
            kayntiosoite: {
                postinumeroUri: 'posti_02100',
                osoiteTyyppi: 'kaynti',
                yhteystietoOid: '1.2.246.562.5.2013112012294919890347',
                maaUri: '',
                postitoimipaikka: 'ESPOO',
                osoite: 'Kökköpolku 980',
                ytjPaivitysPvm: '2015-01-31',
            },
            postiosoite: {
                postinumeroUri: 'posti_02101',
                osoiteTyyppi: 'posti',
                yhteystietoOid: '1.2.246.562.5.2013112012294919824794',
                maaUri: '',
                postitoimipaikka: 'ESPOO',
                osoite: 'Horonpohjantie 530',
                ytjPaivitysPvm: '2017-04-18',
            },
            alkuPvm: '1993-03-19',
            nimi: {
                fi: 'CSC-Tieteen tietotekniikan keskus Oy',
                sv: 'CSC-Tieteen tietotekniikan keskus Oy',
                en: 'CSC-Tieteen tietotekniikan keskus Oy',
            },
            status: 'AKTIIVINEN',
            version: 8,
        },
        {
            lyhytNimi: {
                fi: 'Opetus- ja kulttuuriministeriö',
                sv: 'Opetus- ja kulttuuriministeriö',
                en: 'Opetus- ja kulttuuriministeriö',
            },
            muutKotipaikatUris: [],
            muutOppilaitosTyyppiUris: [],
            yhteystietoArvos: [],
            yritysmuoto: 'Valtio ja sen laitokset',
            piilotettu: false,
            parentOid: '1.2.246.562.10.00000000001',
            parentOidPath: '|1.2.246.562.10.00000000001|',
            oid: '1.2.246.562.10.78946234170',
            kieletUris: ['oppilaitoksenopetuskieli_1#1', 'oppilaitoksenopetuskieli_2#1'],
            kotipaikkaUri: 'kunta_091',
            kuvaus2: {},
            maaUri: 'maatjavaltiot1_fin',
            metadata: {
                data: {
                    KANSAINVALISET_KOULUTUSOHJELMAT: {},
                    YLEISKUVAUS: {},
                    KIELIOPINNOT: {},
                    TERVEYDENHUOLTOPALVELUT: {},
                    TEHTAVANIMIKE: {},
                    SAHKOPOSTIOSOITE: {},
                    RAHOITUS: {},
                    AIEMMIN_HANKITTU_OSAAMINEN: {},
                    'sosiaalinenmedia_7#1': {},
                    'sosiaalinenmedia_5#1': {},
                    'sosiaalinenmedia_6#1': {},
                    OPISKELIJALIIKKUVUUS: {},
                    VAKUUTUKSET: {},
                    OPISKELIJA_JARJESTOT: {},
                    VALINTAMENETTELY: {},
                    'sosiaalinenmedia_3#1': {},
                    'sosiaalinenmedia_4#1': {},
                    'sosiaalinenmedia_1#1': {},
                    VASTUUHENKILOT: {},
                    KUSTANNUKSET: {},
                    OPPIMISYMPARISTO: {},
                    'sosiaalinenmedia_2#1': {},
                    PUHELINNUMERO: {},
                    NIMI: {},
                    OPISKELIJALIIKUNTA: {},
                    VUOSIKELLO: {},
                    OPISKELIJARUOKAILU: {},
                    VAPAA_AIKA: {},
                    ESTEETOMYYS: {},
                    TIETOA_ASUMISESTA: {},
                    TYOHARJOITTELU: {},
                },
                hakutoimistoEctsNimi: {},
                hakutoimistoEctsPuhelin: {},
                hakutoimistoEctsTehtavanimike: {},
                hakutoimistoEctsEmail: {},
                hakutoimistonNimi: {},
                yhteystiedot: [],
                luontiPvm: 1415797301842,
                muokkausPvm: 1415797301842,
                nimi: {},
            },
            nimet: [
                {
                    nimi: {
                        fi: 'Opetus- ja kulttuuriministeriö',
                        sv: 'Opetus- ja kulttuuriministeriö',
                        en: 'Opetus- ja kulttuuriministeriö',
                    },
                    alkuPvm: '2010-05-01',
                    version: 0,
                },
            ],
            toimipistekoodi: '',
            tyypit: ['organisaatiotyyppi_05'],
            vuosiluokat: [],
            lisatiedot: [],
            ryhmatyypit: [],
            kayttoryhmat: [],
            ytjkieli: 'kieli_fi#1',
            ytjpaivitysPvm: '2017-04-18',
            ytunnus: '0245872-8',
            yhteystiedot: [
                {
                    osoiteTyyppi: 'kaynti',
                    kieli: 'kieli_sv#1',
                    postinumeroUri: 'posti_00170',
                    yhteystietoOid: '1.2.246.562.5.68472149678',
                    id: '1825991',
                    postitoimipaikka: 'HELSINGFORS',
                    osoite: 'Polvivaara 992',
                },
                {
                    kieli: 'kieli_sv#1',
                    numero: '050 46787781',
                    tyyppi: 'puhelin',
                    yhteystietoOid: '1.2.246.562.5.75409758515',
                    id: '1825987',
                },
                {
                    osoiteTyyppi: 'kaynti',
                    kieli: 'kieli_fi#1',
                    postinumeroUri: 'posti_00170',
                    yhteystietoOid: '1.2.246.562.5.90508185168',
                    id: '1825990',
                    postitoimipaikka: 'HELSINKI',
                    osoite: 'Livohkankuja 119',
                    ytjPaivitysPvm: '2017-04-06',
                },
                {
                    osoiteTyyppi: 'posti',
                    kieli: 'kieli_sv#1',
                    postinumeroUri: 'posti_00023',
                    yhteystietoOid: '1.2.246.562.5.15058805068',
                    id: '1825992',
                    postitoimipaikka: 'STADSRÅDET',
                    osoite: 'Kuoppamäki 956',
                },
                {
                    kieli: 'kieli_fi#1',
                    yhteystietoOid: '14914685289060.8840672918928975',
                    id: '1825995',
                    email: 'hakija-14075581@oph.fi',
                },
                {
                    osoiteTyyppi: 'posti',
                    kieli: 'kieli_fi#1',
                    postinumeroUri: 'posti_00023',
                    yhteystietoOid: '1.2.246.562.5.75190902503',
                    id: '1825994',
                    postitoimipaikka: 'VALTIONEUVOSTO',
                    osoite: 'Vitsinraitti 448',
                    ytjPaivitysPvm: '2017-04-18',
                },
                {
                    kieli: 'kieli_fi#1',
                    numero: '050 35186791',
                    tyyppi: 'puhelin',
                    yhteystietoOid: '1.2.246.562.5.57121416380',
                    id: '1825988',
                },
            ],
            kayntiosoite: {
                postinumeroUri: 'posti_00170',
                osoiteTyyppi: 'kaynti',
                yhteystietoOid: '1.2.246.562.5.90508185168',
                postitoimipaikka: 'HELSINKI',
                osoite: 'Livohkankuja 119',
                ytjPaivitysPvm: '2017-04-06',
            },
            postiosoite: {
                postinumeroUri: 'posti_00023',
                osoiteTyyppi: 'posti',
                yhteystietoOid: '1.2.246.562.5.75190902503',
                postitoimipaikka: 'VALTIONEUVOSTO',
                osoite: 'Vitsinraitti 448',
                ytjPaivitysPvm: '2017-04-18',
            },
            alkuPvm: '1979-01-02',
            nimi: {
                fi: 'Opetus- ja kulttuuriministeriö',
                sv: 'Opetus- ja kulttuuriministeriö',
                en: 'Opetus- ja kulttuuriministeriö',
            },
            status: 'AKTIIVINEN',
            version: 16,
        },
    ]);
};
